server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kbzcai/aisspringcloud.git
          search-paths: config
          username: 503600776@qq.com
          password: cyj503600776
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

